
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/communic/public_html/
    - /bin/cp -R artifact/* $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets/* $DEPLOYPATH/assets/
    - /bin/cp -R public/* $DEPLOYPATH/public/
